"""Provider registry for Karna.

Maps provider names to their implementation classes and exposes a
``get_provider()`` lookup helper and ``resolve_model()`` parser.
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path
from typing import Any

from karna.providers.base import BaseProvider

# Lazy imports keep startup fast and avoid circular-import issues.
_PROVIDER_PATHS: dict[str, tuple[str, str]] = {
    "openrouter": ("karna.providers.openrouter", "OpenRouterProvider"),
    "openai": ("karna.providers.openai", "OpenAIProvider"),
    "azure": ("karna.providers.azure", "AzureOpenAIProvider"),
    "anthropic": ("karna.providers.anthropic", "AnthropicProvider"),
    "local": ("karna.providers.local", "LocalProvider"),
    "vertex": ("karna.providers.vertex", "VertexProvider"),
    "bedrock": ("karna.providers.bedrock", "BedrockProvider"),
    "failover": ("karna.providers.failover", "FailoverProvider"),
    "moa": ("karna.providers.moa", "MixtureOfAgentsProvider"),
    "router": ("karna.providers.router", "CostAwareRouterProvider"),
}

# Convenience re-export so callers can do ``from karna.providers import PROVIDERS``
PROVIDERS: dict[str, tuple[str, str]] = dict(_PROVIDER_PATHS)

# Default provider when none specified
DEFAULT_PROVIDER = "openrouter"


def get_provider(name: str, **kwargs: Any) -> BaseProvider:
    """Return an *instantiated* provider for *name* (case-insensitive).

    Any extra ``**kwargs`` are forwarded to the provider constructor.
    Raises ``KeyError`` if the provider is not registered.
    """
    key = name.lower()
    if key not in _PROVIDER_PATHS:
        raise KeyError(f"Unknown provider: {name!r}. Available: {', '.join(_PROVIDER_PATHS)}")
    module_path, class_name = _PROVIDER_PATHS[key]
    mod = importlib.import_module(module_path)
    cls = getattr(mod, class_name)
    return cls(**kwargs)


def get_provider_class(name: str) -> type[BaseProvider]:
    """Return the provider **class** for *name* (case-insensitive).

    Raises ``KeyError`` if the provider is not registered.
    """
    key = name.lower()
    if key not in _PROVIDER_PATHS:
        raise KeyError(f"Unknown provider: {name!r}. Available: {', '.join(_PROVIDER_PATHS)}")
    module_path, class_name = _PROVIDER_PATHS[key]
    mod = importlib.import_module(module_path)
    return getattr(mod, class_name)


def resolve_model(model_string: str) -> tuple[str, str]:
    """Parse a ``provider:model`` string into ``(provider_name, model_id)``.

    Examples::

        >>> resolve_model("openrouter:gpt-oss-120b")
        ('openrouter', 'gpt-oss-120b')
        >>> resolve_model("anthropic:claude-sonnet-4-20250514")
        ('anthropic', 'claude-sonnet-4-20250514')
        >>> resolve_model("gpt-4o")
        ('openrouter', 'gpt-4o')

    When no provider prefix is given, defaults to ``openrouter``.
    """
    if ":" in model_string:
        provider, _, model = model_string.partition(":")
        provider = provider.strip().lower()
        model = model.strip()
        if provider in _PROVIDER_PATHS:
            return provider, model
    # No recognized prefix -- default to openrouter
    return DEFAULT_PROVIDER, model_string.strip()


# ─── Canonical model registry (B1) ──────────────────────────────────────────

_CANONICAL_MODELS_PATH = Path(__file__).parent / "canonical_models.json"
_canonical_cache: list[dict[str, Any]] | None = None
_canonical_by_id: dict[str, dict[str, Any]] | None = None


def _load_canonical_models() -> list[dict[str, Any]]:
    """Lazily load and cache the canonical model registry.

    Backing file is generated by ``scripts/build_canonical_models.py`` from
    OpenRouter + HuggingFace + a hand-curated direct-API list. Rebuild when
    a new provider model ships.
    """
    global _canonical_cache, _canonical_by_id
    if _canonical_cache is not None:
        return _canonical_cache
    if not _CANONICAL_MODELS_PATH.exists():
        _canonical_cache = []
        _canonical_by_id = {}
        return _canonical_cache
    _canonical_cache = json.loads(_CANONICAL_MODELS_PATH.read_text())
    _canonical_by_id = {m["id"]: m for m in _canonical_cache}
    return _canonical_cache


def canonical_models() -> list[dict[str, Any]]:
    """Return the full list of canonical model entries (capability-tagged)."""
    return list(_load_canonical_models())


def _normalize_canonical_id(provider: str, model: str) -> str:
    """Collapse ``provider:model`` and ``provider/model`` into the canonical key."""
    if "/" in model:
        return model  # already ``org/model``
    return f"{provider}/{model}"


def model_capabilities(model_string: str) -> dict[str, Any] | None:
    """Look up a model's capabilities from the canonical registry.

    Accepts ``provider:model``, ``org/model``, or bare ``model`` (with the
    default provider applied via ``resolve_model``). Returns ``None`` when the
    model isn't in the registry — callers should treat the absence as
    "capabilities unknown, make no claims" rather than "zero capabilities".
    """
    _load_canonical_models()
    if not _canonical_by_id:
        return None
    provider, model = resolve_model(model_string)
    # Try a series of likely lookup keys, shortest-specific to most-specific.
    candidates = [
        _normalize_canonical_id(provider, model),
        model,
        f"{provider}/{model}",
    ]
    for key in candidates:
        if key in _canonical_by_id:
            return dict(_canonical_by_id[key])
    return None
