[
    [
        "logging.FileHandler('api.log'),\n        logging.StreamHandler()\n    ]\n)\n\n# Initialize FastAPI app\napp = FastAPI(\n    title=\"Government Contract Opportunities API",
        'description="API for querying government contract opportunities',
        'version="1.0.0"\n)\n\n# Initialize database\nopp_db = OpportunityDatabase()\n\n@app.get("/")\nasync def root():\n    "',
        'Root endpoint with API information"',
        '\n    return {\n        "message": "Government Contract Opportunities API',
        'endpoints": {\n            "all_opportunities": "/opportunities',
        'search_opportunities": "/opportunities/search',
        'recent_opportunities": "/opportunities/recent',
        'opportunities_count": "/opportunities/count"\n        }\n    }\n\n@app.get("/opportunities',
        'async def get_opportunities(agency: str = None, keyword: str = None, days_back: int = 30):\n    "',
        'Get all opportunities with optional filters"',
        '\n    try:\n        opportunities = opp_db.query_opportunities(agency=agency, keyword=keyword, days_back=days_back)\n        return {\n            "success',
        True,
        "count",
        'len(opportunities),\n            "data',
        'opportunities\n        }\n    except Exception as e:\n        raise HTTPException(status_code=500, detail=f"Error retrieving opportunities: {str(e)}")\n\n@app.get("/opportunities/recent")\nasync def get_recent_opportunities(limit: int = 10):\n    "',
        'Get most recent opportunities"',
        "\n    try:\n        recent_opps = opp_db.get_recent_opportunities(limit=limit)\n        # Convert DataFrame to list of dictionaries\n        opportunities = recent_opps.to_dict(orient='records') if not recent_opps.empty else []\n        return {\n            \"success",
        True,
        "count",
        'len(opportunities),\n            "data',
        'opportunities\n        }\n    except Exception as e:\n        raise HTTPException(status_code=500, detail=f"Error retrieving recent opportunities: {str(e)}")\n\n@app.get("/opportunities/count")\nasync def get_opportunities_count():\n    "',
        'Get total count of opportunities"',
        '\n    try:\n        count = opp_db.get_opportunities_count()\n        return {\n            "success',
        True,
        "total_opportunities",
        'count\n        }\n    except Exception as e:\n        raise HTTPException(status_code=500, detail=f"Error retrieving count: {str(e)}")\n\n@app.get("/opportunities/search',
        'async def search_opportunities(q: str, agency: str = None, days_back: int = 30):\n    "',
        'Search opportunities by keyword"',
        '\n    try:\n        opportunities = opp_db.query_opportunities(agency=agency, keyword=q, days_back=days_back)\n        return {\n            "success',
        True,
        "query",
        'q,\n            "count',
        'len(opportunities),\n            "data',
        'opportunities\n        }\n    except Exception as e:\n        raise HTTPException(status_code=500, detail=f"Error searching opportunities: {str(e)}")\n\n@app.post("/scrape")\nasync def run_scrape():\n    "',
        'Trigger a manual scrape (for testing purposes)"',
        '\n    try:\n        # This would run the actual scraper\n        # In a real implementation, this would call the scraper functions\n        return {\n            "success',
        True,
        'message": "Scraping initiated. Check back later for results.',
    ],
    {"__main__": "print(", 'host="0.0.0.0': "port=8000)"},
]
