[
    ["datetime", "logging", "sqlite3", "pandas as pd"],
    {
        "class GovContractScraper": "def __init__(self, db_path='opportunities.db'):",
        "self.db_path": "db_path",
        "self.init_database": "def init_database(self):",
        "conn = sqlite3.connect(self.db_path)": "cursor = conn.cursor()",
        "cursor.execute('''": "CREATE TABLE IF NOT EXISTS opportunities (",
        "id INTEGER PRIMARY KEY AUTOINCREMENT": "title TEXT NOT NULL",
        "agency TEXT": "posted_date TEXT",
        "due_date TEXT": "description TEXT",
        "link TEXT": "source TEXT",
        "scraped_date TEXT": "",
        ", 'conn.commit": "conn.close",
        'logging.info("Database initialized successfully': "def scrape_sam_gov(self):",
        "logging.info('Scraping SAM.gov opportunities": "opportunities = [",
        "title": "Public Health Data Analysis Contract",
        "agency": "CDC",
        "posted_date": "2026-04-18",
        "due_date": "2026-05-15",
        "description": "Contract for analyzing public health datasets",
        "link": "https://sam.gov/opportunity/12345",
        "source": "SAM.gov':",
    },
    "], {'title': 'Health Research Services",
    "agency': 'NIH",
    "posted_date': '2026-04-17",
    "due_date': '2026-05-20",
    "description': 'Research services for public health initiatives",
    "link': 'https://fedbizopps.gov/opportunity/67890",
    "source': 'FedBizOpps': 'return opportunities",
    "def save_opportunities(self, opportunities': 'conn = sqlite3.connect(self.db_path)",
    "cursor = conn.cursor': 'scraped_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')",
    "for opp in opportunities': \"cursor.execute('",
    "\", 'INSERT INTO opportunities':",
    "title, agency, posted_date, due_date, description, link, source, scraped_date', 'VALUES (?, ?, ?, ?, ?, ?, ?, ?': 'opp.get('title', '')', 'opp.get('agency', '')': 'opp.get('posted_date', '')', 'opp.get('due_date', '')': 'opp.get('description', '')', 'opp.get('link', '')': 'opp.get('source', '')', 'scraped_date': '', 'conn.commit': 'conn.close', 'logging.info(f",
    "Saved {len(opportunities': 'opportunities', 'def run_daily_scrape(self': 'logging.info(",
    "Starting daily government contract scrape', 'all_opportunities': 'sam_opps = self.scrape_sam_gov', 'fedbiz_opps': 'self.scrape_fedbizopps', 'all_opportunities.extend(sam_opps': 'all_opportunities.extend(fedbiz_opps', 'if all_opportunities': 'self.save_opportunities(all_opportunities', 'logging.info(",
    "Daily scrape completed': 'def get_daily_report(self):', 'conn = sqlite3.connect(self.db_path': \"query = '''",
    "SELECT * FROM opportunities': \"WHERE scraped_date >= date('now",
    "-1 day\", 'ORDER BY scraped_date DESC': \"'",
    '",',
    "df = pd.read_sql_query(query, conn': 'conn.close', 'return df'], {'def main': 'scraper = GovContractScraper', 'scraper.run_daily_scrape': '', '__main__': 'main'}]",
]
